#4 feat: 유저 엔티티 생성
choorai/excuse-me-backend pull request #15
Opened 2024-01-06 13:45 UTC by somefood

- flyway는 버전 넘버링을 할 때 단순1부터 증가하는 방식과 날짜로 지정하는 방식이 있길래 날짜로 해보았습니다.
근데 생각해보니 날짜로해도 같은 날에 여러 개 만들 수도 있으니 숫자도 같이 추가하는게 좋을거 같은데 의견들 궁금합니다!

- 웬만한 테이블 컬럼엔 생성, 수정 날짜들이 들어가니 BaseEntity를 만들었습니다.

- close #4

2024-01-06 13:58 UTC, xi-jjun requested changes
index도 추가해주세요!

2024-01-06 13:58 UTC, xi-jjun commented on src/main/resources/db/migration/V20240106__create_member_table.sql
> +    username varchar(50)                    NOT NULL UNIQUE,
username에 50자 제한을 거신 이유가 있으실까요?

2024-01-06 13:58 UTC, xi-jjun commented on src/main/resources/db/migration/V20240106__create_member_table.sql
> +    password varchar(100)                   NOT NULL,
개인적으로 이유가 없다면 제한을 거는 것은 안좋을 것 같습니다
- 결국 비밀번호를 인코딩하여 저장하게 될 것인데, 100자가 넘어아게되면 추가적인 작업이 요구됨.
- 100자를 함으로써 DB 디스크 사용량을 줄이는 것 보다 제약사항이 더 손해가 커 보여서 굳이 제한을 안해도 될 것으로 보임.

위 2가지 이유로 저는 255로 써도 될 것 같습니다 ㅎㅎㅎ(기본값)

2024-01-06 14:47 UTC, seokhwan-an reviewed
member 엔티티를 구성하시느라 고생하셨습니다!
간단한 리뷰와 함께 질문 남겼습니다.
아까 저는 flyway 버전관리하는 것 날짜로 하는 것이 좋을 것 같다고 했는데 pr 메세지를 보니 하루에 여러변 변화하는 경우를 고려하면 번호로 버전관리하는 것이 더 좋은 방안인 것 같습니다!

2024-01-06 14:47 UTC, seokhwan-an commented on src/main/resources/db/migration/V20240106__create_member_table.sql
> +    username varchar(50)                    NOT NULL UNIQUE,
username에 Unique 제약조건을 거신 이유는 이메일 정보를 username으로 저장하기 때문인가요?

2024-01-06 14:47 UTC, seokhwan-an commented on src/main/resources/db/migration/V20240106__create_member_table.sql
> +)
마지막에 공백 라인하나 추가해주세요
그 이유는 [파일-끝에-개행을-추가해야-하는-이유](https://coderifleman.tumblr.com/post/115464362564/%ED%8C%8C%EC%9D%BC-%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%B6%94%EA%B0%80%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0) 한번 보시면 좋을 것 같습니다!

2024-01-06 14:47 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/domain/Member.java
> +
여기 공백 한 줄 제거해주세요!!

2024-01-07 13:47 UTC, JoungMinJu approved these changes

2024-01-07 14:22 UTC, somefood commented on src/main/resources/db/migration/V20240106__create_member_table.sql
> +    password varchar(100)                   NOT NULL,
아하 기본값이 255이군요!
단순하게 화면에서 보통 쓰이는 제약에 맞춰서 제 임의로 지정했었는데,
기본값으로 적용해보겠습니다!

2024-01-07 14:24 UTC, xi-jjun reviewed
석환님도 언급해주셨지만, flyway의 버저닝에 관련해서는 날짜까지만 나와 있으면 무조건 겹칠 수 있기 때문에 `V년월_시분__create_xxx` 로 해주시는게 좋을 것 같아요

2024-01-07 14:25 UTC, somefood commented on src/main/resources/db/migration/V20240106__create_member_table.sql
> +    username varchar(50)                    NOT NULL UNIQUE,
> username에 Unique 제약조건을 거신 이유는 이메일 정보를 username으로 저장하기 때문인가요?

넵 맞습니다.
이슈의 참고사항에서 email을 유저 아이디로 받자는 의견이 있어서 유니크 제약을 걸었습니다.

2024-01-07 14:26 UTC, xi-jjun requested changes

2024-01-07 14:26 UTC, xi-jjun commented on src/main/java/choorai/excuseme/member/domain/Member.java
> +    private String username;
unique 제약사항을 걸었는데, 어플리케이션 레벨의 코드에선 해당 설정이 보이지 않네요.
추가해주시길 바라겠습니다!

2024-01-07 14:30 UTC, somefood commented
> 석환님도 언급해주셨지만, flyway의 버저닝에 관련해서는 날짜까지만 나와 있으면 무조건 겹칠 수 있기 때문에 `V년월_시분__create_xxx` 로 해주시는게 좋을 것 같아요

넵 저도 단순 넘버링만 하면 해당 DDL이 언제 작성됐는지 모를 수 있을거 같아서 시분까지는 넣어주는게 좋을거 같네요.
이렇게 수정토록 해보겠습니다.

2024-01-07 14:32 UTC, somefood commented
> index도 추가해주세요!

혹시 인덱스를 username 쪽으로 생각하신 건가요?
유니크 제약을 걸면 인덱스가 자동으로 생성된다 알고있어서 한 번 문의드립니다 ㅎㅎ

2024-01-07 17:19 UTC, xi-jjun commented
> @xi-jjun 혹시 인덱스를 username 쪽으로 생각하신 건가요?
유니크 제약을 걸면 인덱스가 자동으로 생성된다 알고있어서 한 번 문의드립니다 ㅎㅎ

현재 해주신 부분은 DB 레벨에서만 해주었고, table에서 유니크 인덱스를 생성하는 명시적 코드를 추가해달라는 뜻이었어요.
https://velog.io/@hwan2da/JPA-Columnuniquetrue-UniqueConstraints 참고하셔서 진행해주세요.
현재는 unique 인덱스의 이름이 코드 상에는 드러나지 않아서 향후 생길 수 있는 혼란을 방지하고자 함도 있고, jpa validate라는 옵셥을 사용했기에 DB와 entity설정이 다르면 어플리케이션이 실행되지 않을 수도 있기 때문입니다.

2024-01-07 17:19 UTC, xi-jjun requested changes

2024-01-07 17:19 UTC, xi-jjun commented on src/main/resources/db/migration/V20230107_1135__create_member_table.sql
> +    username   varchar(255)                      NOT NULL UNIQUE,
index 이름도 명시적으로 선언해주세요!

2024-01-08 14:00 UTC, seokhwan-an commented on src/main/resources/db/migration/V20240106__create_member_table.sql
> +    username varchar(50)                    NOT NULL UNIQUE,
확인했습니다!

2024-01-08 15:26 UTC, somefood commented on src/main/resources/db/migration/V20230107_1135__create_member_table.sql
> +    username   varchar(255)                      NOT NULL UNIQUE,
867ea00048109d78f8e2fdefae10db0919a10c5b

의도한대로 적용된건지 확인 한번 부탁드리겠습니다!

2024-01-08 16:27 UTC, xi-jjun commented on src/main/resources/db/migration/V20230107_1135__create_member_table.sql
> +    username   varchar(255)                      NOT NULL UNIQUE,
https://herojoon-dev.tistory.com/142 참고하셔서 진행해주세요!

2024-01-10 05:01 UTC, seokhwan-an approved these changes
리뷰 반영된 것 모두 확인했습니다.
고생하셨습니다!

[다시 코드를 본 후 리뷰남깁니다!]
username읜 경우 unique 필드이기 때문에 unique 인덱스를 설정하면 좋을 것 같습니다!

2024-01-13 17:50 UTC, xi-jjun requested changes

2024-01-13 17:50 UTC, xi-jjun commented on src/main/java/choorai/excuseme/member/domain/Member.java
> +        @Index(name = "idx_id", columnList = "id"),
PK는 필요없습니다..

2024-01-13 17:50 UTC, xi-jjun commented on src/main/resources/db/migration/V20230107_1135__create_member_table.sql
> +    CONSTRAINT idx_id PRIMARY KEY (id),
PK는 이름설정이 필요없습니다

2024-01-14 04:23 UTC, xi-jjun approved these changes
수고하셨습니다~!

2024-01-14 11:26 UTC, merged