Feature/#6 add jwt token
choorai/excuse-me-backend pull request #23
Opened 2024-01-21 12:35 UTC by somefood

초간단 회원가입 및 로그인 시 JWT 액세스 토큰을 발급 받아보도록 했습니다.

인터넷 참고해보며 만든거라 더 다듬어야할거 같은데, 1차적으로 이런 느낌으로 만들어보았다 보여드리려고 PR 한 번 작성해드립니다.
추후에 validator도 추가해서 유효성 체크도 해야할거 같습니다.
그리고 서비스 코드에서 @seokhwan-an 석환님이 만든 ErrorCode를 즉흥으로 추상 클래스로 implement 해서 만들었는데,, 에러 코드 클래스를 어떤식으로 관리하면 될지 의견 한 번 여쭙니다!

- 회원가입 시 (중복 유저인 경우)
<img width="487" alt="image" src="https://github.com/choorai/excuse-me-backend/assets/24751937/e35cdeeb-0f26-422c-83b6-8c9b655e61b2">

- 로그인 시
<img width="1167" alt="image" src="https://github.com/choorai/excuse-me-backend/assets/24751937/a0eeb11b-a88e-4486-a26a-f022d5dbb959">

2024-01-21 13:15 UTC, xi-jjun commented on src/main/java/choorai/excuseme/member/ui/MemberController.java
> +public class MemberController {
오, 혹시 ui라는 package 구조는 어디서 참고하신것일까요

2024-01-22 13:31 UTC, JoungMinJu reviewed
궁금한거 몇 개만 일단 리뷰 달아놓겠습니다!!

2024-01-22 13:31 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +package choorai.excuseme.member.application;
application / domain / service / ui 로 프로젝트 구조가 나뉘어지는데 각각 역할이 궁금합니다!!!!!!

2024-01-22 13:31 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/domain/dto/SignResponse.java
> +import choorai.excuseme.member.domain.Member;
요거 Member 임포트 불필요해보입니데이!

2024-01-22 13:31 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User not found"));
저는 custom exception이 좀 더 명시적인 정보를 전달할 수 있다는 점에서 선호하는 편인데요! 그래서 이렇게 커스텀 예외 사용하는거 너무너무 찬성이어요 ^________^

그래서 그런데 혹시 new UsernameNotFoundException()에선 왜 커스텀 예외를 사용하지 않으셨는지 여쭤봐도 될까요?? 기냥 단순하게 궁금해서 리뷰 남깁니다 ! 기본 예외로도 충분히 정보를 제공할 수 있어서 그런건가요?!?!

2024-01-23 00:52 UTC, somefood commented on src/main/java/choorai/excuseme/member/ui/MemberController.java
> +public class MemberController {
석환님의 우테코 프로젝트 보고 모방했습니다 ㅎㅎ

2024-01-23 07:49 UTC, seokhwan-an requested changes
먼저 spring security와 jwt 토큰 관련한 처리하시느라 고생 많으셨습니다!👍👍
코드에 대한 리뷰와 의견을 묻는 것을 남겨두었습니다! 
시간 나실 때 확인해주세요! 혹시 이해가 안되는 부분이 있다면 편하게 연락주세요!

2024-01-23 07:49 UTC, seokhwan-an commented on build.gradle
> +	implementation group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'
혹시 이 부분은 다른 dependency와 다르게 `group:` , `name:`, `version:`으로 명시적으로 작성한 이유가 있나요?

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +                });
이 부분을 살펴보면 JwtAuthenticationFilter에서 예외상황이 발생하는 경우 처리방식을 나타낸 것 같습니다. 이 부분은 SecurityConfig에 노출시키는 것 보다는 JwtAuthenticationFilter 내부에서 예외를 발생시키는 것이 좋을 것 같습니다!

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtAuthenticationFilter.java
> +    }
앞서서 남긴 예외처리를 이 부분에 추가하면 될 것 같습니다! 이 부분에서 예외를 발생시키고 이를 스프링에서 처리하도록 하기 위해서는 JwtAuthenticationFilter도 bean으로 등록시켜야 할 것 같아요!

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +                });
등록되는 필터가 많아지는 경우에 필터마다 예외사항을 노출시키면 securityConfig가 무거워질 것 같습니다!

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
> +    }
현재 이 메소드는 외부에서 이용되는 것이 아닌 내부의 `getAuthentication`에서만 이용되어서 private로 변경해주세요!☺️

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
> +    private static final String prefix = "BEARER ";
클래스 변수가 다른 변수들보다 더 위에 있도록 수정부탁드립니다!☺️

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
> +    }
74번째 줄은 token의 시작이 `Bearer ` 인지를 체크하는 부분인 것 같습니다.
이 부분은 아래와 같이 수정하면 가독성이 더 좋아질 것 같습니다.
```java
if (!token.startsWith(prefix))
```

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
> +    }
78번줄과 79번줄은 현재 `.`이 많아서 가독성이 좋지 않은 것 같습니다.
한 줄에 `.` 한 개만 남기고 줄바꿈을 경우 validateToken 메소드가 길게 느껴진다면 78번 줄과 79번 줄의 경우는 메소드 분리를 하시면 될 것 같습니다!☺️

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/domain/Authority.java
> +}
혹시 이 authority라는 객체를 만든 이유가 member가 여러 authority를 가지는 경우 제1정규형을 지키기 위해 만든 것인지 궁금합니다. 현재 요구사항에서는 member가 여러 authority를 가지는 사항이 없는 것 같아서 member Authority라는 필드 하나만 추가 되면 될 것 같다는 생각이 드는데 다른 이유가 있으면 말해주세요!☺️

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +
리뷰요청 시 질문드렸던 부분에 대해서 답변 남깁니다.
제가 ErrorCode를 Enum이 아닌 Interface로 만든 이유는 예외 사항을 각 도메인에서 관리할 수 있게 하기 위함이었습니다.
Enum으로 모든 ErrorCode를 관리하면 한 파일로 관리할 수 있다는 장점이 있지만 ErrorCode가 많아지게 된다면 관리하기 어렵다는 점이 있습니다. 그래서 각 도메인에서 ErrorCode를 구현한 객체를 만들고 각 도메인에 관련된 예러를 관리하기 위함입니다.
현재 코드를 예시로 들겠습니다. Member 객체에서 발생하는 예외이므로 Member 패키지 내부에서 exception 패키지를 만들고 거기에 아래와 같은 객체를 만듭니다.
**MemberErrorCode.java**
```java
package choorai.excuseme.member.exception;

import choorai.excuseme.global.exception.ErrorCode;
import org.springframework.http.HttpStatus;

public enum MemerErrorCode implements ErrorCode {

    WRONG_PASSWORD(HttpStatus.BAD_REQUEST, "잘못된 입력", "올바르지 않는 패스워드 입니다.");

    private final HttpStatus httpStatus;
    private final String errorCode;
    private final String errorMessage;

    MemerErrorCode(HttpStatus httpStatus, String errorCode, String errorMessage) {
        this.httpStatus = httpStatus;
        this.errorCode = errorCode;
        this.errorMessage = errorMessage;
    }

    @Override
    public HttpStatus getHttpStatus() {
        return null;
    }

    @Override
    public String getCode() {
        return null;
    }

    @Override
    public String getMessage() {
        return null;
    }
}
```
**MemberException.java**
```java
package choorai.excuseme.member.exception;

import choorai.excuseme.global.exception.CommonException;
import choorai.excuseme.global.exception.ErrorCode;

import java.util.Map;

public class MemberException extends CommonException {

    public MemberException(ErrorCode errorCode, Map<String, Object> additionalInfos) {
        super(errorCode, additionalInfos);
    }

    public MemberException(ErrorCode errorCode) {
        super(errorCode);
    }
}

```
이렇게 한 다음에 기존의 코드는 아래와 같이 변경하면 됩니다.
```java
 if (!passwordEncoder.matches(signRequest.getPassword(), foundMember.getPassword())) {
        throw new MemberException(MemerErrorCode.WRONG_PASSWORD);
        // 혹은 new MemberException(MemerErrorCode.WRONG_PASSWORD, Map.of())
        // Map에는 로그에 찍을 정보를 넣으면 됩니다.
    }
```

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +            });
여기도 위에서 한 것처럼 처리하면 될 것 같습니다!☺️

2024-01-23 07:49 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/domain/Member.java
> +    }
혹시 생성자보다 메소드들을 위에 두는 편이신가요?

2024-01-25 01:32 UTC, somefood reviewed
리뷰 반영했습니다. 확인 한 번 부탁드리겠습니다!

펜딩 되는걸 첨 봐서 안 보이실줄 몰랐습니다.
죄송함미다 ㅠㅠ

2024-01-25 01:32 UTC, somefood commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User not found"));
엄 사실 제가 만든 서비스는 단순하게 JWT 토큰이 잘 작동하는지 테스트하기 위해서 만든 임시 코드들이라 보시면 됩니다. 임시로 만들면서 석환님이 만든 커스텀도 써보고 사전에 정의된 Exception을 써본겁니다.

제가 어디서 주워들은거긴 한데, 사전에 잘 만들어진 예외를 사용하는 것도 중요하다고 합니다.
가령, 유효하지 않은 인자들이 들어오면 IllegalArgumentException이나, 위와 같이 유저를 찾을 수 없으면 UsernameNotFounException을 사용하듯, 명시적인 이름으로 예외를 던지면 대략 어떤 점으로 문제가 생겼구나를 파악할 수 있기 때문입니다. 대신 예외를 명시적으로 한 만큼 ControllerAdvice에서도 처리해줘야할게 많을거 같습니다 (또는 RuntimeException 통으로 처리 시키거나)

물론 석환님이 만든 CustomeException이 인터페이스이니 비슷한 이름으로 implementation 해도 될거고, 방법은 여러가지인거 같으니 맞춰보는 방향으로 가면 좋을거 같습니다! :)

2024-01-25 01:32 UTC, somefood commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +package choorai.excuseme.member.application;
이게 석환님의 우테코 프로젝트에서 구조가 좋아보여서 모방한거라 사실 저도 깊게 생각은 안해봤는데,
application: 비즈니스 코드가 담기는 패키지
domain: 엔티티나 DAO등이 담기는 패키지
service (지운거 같은데 남아있나보네요. application으로 변경했습니다)
ui: controller 등이 담기는 패키지

왜 위와 같이 잡았는지 개인적인 생각을 말씀드리자면, 좀 더 포괄적인 의미로 패키지 네이밍을 잡은거 같습니다.
저희가 보통 MVC 패턴으로 패키지를 잡으면 controller, service, repository 요런식으로 잡잖아요.
그리고 클래스들의 이름도 OOController, OOService, OORepository 요렇게 잡아서 비즈니스 코드는 service에 DB에 접근하는 코드들은 repository에 집어넣고...
근데 DB에 접근하는 방식이 추가적으로 MyBatis 방식이 필요하다하면 OOMapper로 이름짓거나, JDBCTemplate을 쓴다면 OOTemplate으로 쓸 수 있을텐데 repository 패키지면 뭔가 Repository만 집어넣어야 하는 느낌이 오다보니 포괄적으로 dao라는 패키지를 만들고 안에 다 집어넣으면 덜 어색한 느낌이 들도록 할 수 있을거 같습니다. (저만 그럴지도,,)

어찌됐건 위에 service도 같은 맥락으로 객체들을 분리하면서 유틸성 클래스가 들어올 수도 있으니 좀 더 포괄적인 의미로 application 패키지로 지칭하게 된 듯 합니다.

어디까지나 제 뇌피셜이니... @seokhwan-an 석환님께 부가 설명 토스 좀 부탁드립니다 ㅎㅎ (__)

2024-01-25 01:32 UTC, somefood commented on src/main/java/choorai/excuseme/member/domain/Member.java
> +    }
웁스 원레 저도 메서드 이전에 올려두는데 IDE 단축키로 만들다 보니 놓쳤군요 수정하겠습니다! ㅎㅎ

2024-01-25 01:32 UTC, somefood commented on build.gradle
> +	implementation group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'
이 예제 저 예제 따라하면서 mavenreposiotry에서 붙이다 보니 일관적이지 않게 붙였군요.
통일감있게 맞추겠습니다!

2024-01-25 01:32 UTC, somefood commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
> +    }
한 번 분리해보겠습니다!

2024-01-25 01:32 UTC, somefood commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +
오오 enum도 인터페이스를 구현할 수 있군요.
써본적이 없었는데, 이렇게 할 수 있다니 한 수 배워갑니다.
석환님이 만든 인터페이스를 잘 활용하면 도메인 별로 예외 관리 하기 좋겠군요.
감사합니다! ㅎㅎ

2024-01-25 01:32 UTC, somefood commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +                });
exceptionHandling에서 accessDeniedHandler를 등록했는데, 이 핸들러는 인가 에러난 경우 동작한다고 합니다.
제가 찾아본 예제에서도 이를 의도해서 밖으로 빼둔거 같긴 합니다.

석환님이 말씀하는 예외의 경우는 JWT 토큰이 Malformed, SignatureException 등 같은 예외에 대한 처리를 의미하시는건지 궁금합니다~!

2024-01-25 01:32 UTC, somefood commented on src/main/java/choorai/excuseme/global/security/JwtAuthenticationFilter.java
> +    }
옷 이 부분은 잘 몰라서 그런데 Filter를 빈으로 등록하면 스프링의 ControllerAdivce에서 처리할 수 있는건지요?? 관련 레퍼런스 있으시다면 공유주시면 감사하겠습니다!

2024-01-25 01:32 UTC, somefood commented on src/main/java/choorai/excuseme/member/domain/Authority.java
> +}
음 석환님 말씀대로 한 멤버가 여러 권한을 가질거 같진 않기에 저렇게 1대다 관계를 구성할 필요는 없을거 같네요..!
@JoungMinJu 민주님도 의견 주시면 따로 엔티티로 안빼고 String 형태로 관리하겠습니다~!

2024-01-25 13:49 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User not found"));
넹 같이 정해서 토의해보며 ㄴ좋을 것 같아요!

2024-01-25 13:51 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/domain/Authority.java
> +}
String 형태 관리가 더 편해 보입니다 !!

2024-01-25 13:51 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/application/MemberService.java
> +
야무지다 ..................

2024-01-26 04:52 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +                });
이 부분 제가 테스트를 통해서 확인해보았는데 filter에서 발생한 에러는 Spring Context에서 관리하는 것이 아니기 때문에 커스텀 예외 응답값으로 전달되지 않네요! 잘못된 리뷰를 남겼네요. 앞으로는 더 꼼꼼하게 체크해서 리뷰 남기겠습니다!

2024-01-26 04:52 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtAuthenticationFilter.java
> +    }
이 부분 제가 테스트를 통해서 확인해보았는데 filter에서 발생한 에러는 Spring Context에서 관리하는 것이 아니기 때문에 커스텀 예외 응답값으로 전달되지 않네요! 잘못된 리뷰를 남겼네요. 앞으로는 더 꼼꼼하게 체크해서 리뷰 남기겠습니다!

2024-01-26 04:53 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +                });
이 부분에 대한 리뷰는 넘겨도 될 것 같습니다!

2024-01-26 05:24 UTC, seokhwan-an requested changes
먼저 코드 리뷰 반영하시느라 고생 많으셨습니다!
어제 미팅을 통해서 이야기 나눈 것 (member의 authority)과 더불어 수정할 부분에 대해서 간단하게 리뷰 남겼습니다. 
전에 제가 리뷰로 남겼던 filter 내부에 예외를 처리하는 것에 대해서는 잘 못 남긴 리뷰이니 반영하지 말아주세요!

2024-01-26 05:24 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
>      @Value("${jwt.secret.key}")
여기 사이에 개행 한 줄 추가해 주세요!

2024-01-26 05:24 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
> +    private static boolean isExpired(Jws<Claims> claims) {
이 메소드는 static 메소드 일 필요가 없을 것 같습니다!☺️

2024-01-26 05:26 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/domain/Authority.java
> +}
혹시 String 보다는 enum으로 관리하는 것에 대해서는 어떻게 생각하시나요? 일반 사용자, 관리자 사용자 이렇게 분류가 될 것 같은데 이는 카테고리와 느낌이 비슷해서 단순하게 String 보다는 enum이 더 적절해 보이는데 어떻게 다른 분들은 어떻게 생각하시나요?

2024-01-26 10:20 UTC, JoungMinJu approved these changes

2024-01-27 12:12 UTC, somefood commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
>      @Value("${jwt.secret.key}")
넵 확인했습니다!

2024-01-27 12:12 UTC, somefood commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
> +    private static boolean isExpired(Jws<Claims> claims) {
넵 확인했습니다!

2024-01-30 06:01 UTC, seokhwan-an approved these changes
수정한 것 모두 확인했습니다. 
제가 처음에 확인하지 못했던 것에 대해서 질문하나 남겼고 나머지는 불필요한 import 문 제거하는 리뷰 남겼습니다. 질문에 대해서 다른 의견이 있으면 답변만 남겨주시고 merge 하면 될 것 같습니다.

2024-01-30 06:01 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/CustomUserDetails.java
> +import java.util.Collections;
불필요한 import 문은 제거해 주세요!☺️

2024-01-30 06:01 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JwtProvider.java
> +import java.nio.charset.StandardCharsets;
여기도 불필요한 import 제거해주세요!☺️

2024-01-30 06:01 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/security/JpaUserDetailsService.java
> +    }
이 부분은 token에 넘어온 정보가 실제로 존재하는 멤버인지 파악할 때 이용하는 메소드 인 것 같습니다. 현재 이 부분은 custom 예외를 이용하지 않으셨는데 이 정보는 따로 클라이언트에게 정보를 제공할 필요가 없다고 생각해서 그렇게 하신 걸까요? 
제 생각은 이 부분에서 custom 예외를 제공해(잘못된 토큰을 가지고 있습니다 와 같은 정보) 다시 로그인할 수 있는 트리거를 제공할 것 같습니다. 혹시 다른 의견있으면 말해주세요!

2024-01-30 15:53 UTC, somefood commented on src/main/java/choorai/excuseme/global/security/JpaUserDetailsService.java
> +    }
loadUserByUsername은 Spring Secuirty의 UserDetailsService 인터페이스의 구현부분입니다.
메서드를 보시면 throws UsernameNotFoundException을 던지게끔 되어있기에 되어있어 해당 예외를 던지게끔 유도하고 있습니다.

https://stackoverflow.com/questions/59417122/how-to-handle-usernamenotfoundexception-spring-security
해당 스택오버플로우를 보시면 시큐리티는 컨트롤러와 어드바이스 이전의 레이어이기 때문에, 어드바이스를 통해서 해결하긴 어렵고 
AccessDeniedHanlder 또는 AuthenticationEntryPoint를 활용해서 처리하고 있습니다.

이번 피드백을 보고 위 둘 인터페이스를 구현해서 SecurityConfig에 등록했습니다.
둘의 쓰임새가 차이는 조금 있을거 같은데,, 그 부분은 추후 더 사용하면서 변경해보도록 하겠으며, HttpServletResponse 에서 응답값을 조작해주어야 하는지라 응답값 포맷을 석환님이 만들 틀과 유사하게 만들어 두었습니다. 이 부분만 확인되면 최종 머지토록 하겠습니다!

2024-01-31 11:09 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +
수고가 많으십니다 . . . . 관련 개념 서치하다가 블로그에서 코드를 봤는데 

<img width="894" alt="스크린샷 2024-01-31 오후 8 04 03" src="https://github.com/choorai/excuse-me-backend/assets/81295661/bbc0f7ef-44f0-4be1-b89d-27e76126c197">

구현체에 @Component 달고 주입받는게 좀 더 깔끔해보이더라구요!
꼭 이렇게 바꿔줬음 좋겠다 싶어서 다는 리뷰는 아니지만! 혹시 몰라 코멘트 달아봅니다 

[참조 블로그](https://kim-jong-hyun.tistory.com/36)

2024-02-01 01:21 UTC, merged