#9 구글 OAuth
choorai/excuse-me-backend pull request #24
Opened 2024-02-02 18:08 UTC by JoungMinJu

구글 OAuth 로그인 추가했습니다.

## 1. 전체적인 흐름
![image](https://github.com/choorai/excuse-me-backend/assets/81295661/239e45b7-bd33-40a9-bbac-e7f790eec586)
위 사진과 같이, 안드로이드에서 발급된 access token을 받으면  Google에서 user 정보 (이메일)을 가져오고

해당 이메일이 없으면 -> 회원가입 후 로그인(jwt 토큰 전달)
있으면 -> 로그인(jwt 토큰 전달)

하는 로직으로 구현했습니다!!

## 2. postman 

<img width="622" alt="스크린샷 2024-02-03 오전 2 48 30" src="https://github.com/choorai/excuse-me-backend/assets/81295661/2b668786-9ddf-424b-9e39-50ea62dd53a5">

### access token은

구글 클라우드에 클라이언트 등록해서 발급받아 사용하시면 됩니다! 

## 3. 고민

### (1) Member가 가져야하는 정보
현재는 google에서 username만 가져와서, 해당 이메일의 존재여부를 기반으로 로그인 혹은 회원가입을 진행하는 상황입니다.
그런데 어떤 블로그에선 (이메일, provider)로 user를 식별하더라구요!  혹시 저희도 provider 정보를 추가해야할까요??
카카오 oauth로 가져온 이메일 정보가 "~@gmail.com"일 가능성은 매우 적어보이지만 . . 유의미한 정보가 될 수도 있을 것 같아 의견 여쭤봅니다. (* provider라는 정보가 아래 3번 고민의 해결책이 되지 않을까 싶기도 합니데이)

### (2) OAuth 로그인했을 때 신규 가입자인 경우 진행되는 로직
위에서 말씀드린대로, Oauth를 통해 가져온 username(이메일)이 기존에 등록되지 않은 username이면 memberService.register()를 타게 됩니다. 
이 경우 register될 때 입력되는 password 값을 빈문자열("")로 지정해놓은 상황인데요. 이게 맞는건지 잘 모르겠습니다 🥹 
서치를 엄청나게 해봤는데 딱히 찾아지는게 없었어서 .. 아시는 분 있으시면 의견 주심 감사드리겠습니다.

### (3) 발생할 수 있는 문제 상황
이건 제가 구현하다가 생각한 건인데요 (위의 고민들과도 연결됩니다)

유저 A가 "a@gmail.com"이라는 username, "a"라는 password로 일반로그인을 진행한 상황일 때
이 사람이 "a@gmail.com"으로 구글에 로그인을 해서 Google OAuth를 진행하게 된다면 (구글 OAuth는 처음 시도하는 상태) 자동으로 로그인 로직을 타게 됩니다.
하지만 OAuth에서 로그인 로직을 탈 때 input으로 들어가는 비밀번호가 빈 문자열("")이기 때문에 비밀번호 불일치로 로그인이 되지 않을 것입니다.

이 경우 로그인이 안되는게 맞는건지.............아님 되어야하는건지................."일반회원가입 이후 로그인"과 "oauth 로그인"은 같은 username이라도 다른 유저로 보는 것이 맞는건지 .................. 전혀 모르겠삽니다 ㅠ ㅠ 너무 헷갈려요

## _
password를 어떻게 처리해야하는지 너무 고민스러워서 계속 헤맸는데, 일단 올려놓고 의견 나눠보는 것이 가장 좋을 것 같아 pr 올려봅니다
두서없는 글이지만 확인해주심 감사드리겠습니다 !  !! !

2024-02-04 13:08 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/ui/MemberController.java
> +    @PostMapping("/oauth/login")
좀 더 생각해봤는데 url에 kakao, google 같은 정보 넣게 바꾸는게 좋을 것 같아용 (redirect url 지정할 때 편하려고)

2024-02-04 14:31 UTC, somefood commented
기능 만드시느라 고생하셨습니다.
코드 한 번 확인해보겠습니다~! :)

2024-02-04 14:58 UTC, somefood commented on src/main/java/choorai/excuseme/member/domain/oauth/GoogleUser.java
> +@Builder
Builder 어노테이션이 선언되고 사용이 안 되고 있는거 같은데 사용하신 이유가 궁금합니다!

2024-02-04 14:58 UTC, somefood commented on src/main/java/choorai/excuseme/member/domain/dto/SignRequest.java
> +@Builder
Builder 어노테이션이 선언되고 사용이 안 되고 있는거 같은데 사용하신 이유가 궁금합니다!

2024-02-04 14:58 UTC, somefood commented on src/main/java/choorai/excuseme/member/application/GoogleOAuthService.java
> +        return  objectMapper.readValue(userInfoResponse.getBody(), GoogleUser.class);
return  objectMapper

위 부분 두번 띄어쓰기 된거 같습니다!
확인 부탁드립니다!

2024-02-04 14:58 UTC, somefood commented on src/main/java/choorai/excuseme/member/application/GoogleOAuthService.java
> +        headers.set("Authorization","Bearer "+accessToken);
"Bearer "+accessToekn 도 띄어쓰기 한 번 부탁드립니다!

2024-02-04 14:58 UTC, somefood commented on src/main/java/choorai/excuseme/member/ui/MemberController.java
> +    @PostMapping("/oauth/login")
저도 쿼리 스트링으로 해도 생각이 되면서 이 부분은 클라이언트랑 한 번 맞춰봐야 할 거 같다는 생각이 듭니다 ㅎㅎ

2024-02-04 14:58 UTC, somefood commented on src/main/java/choorai/excuseme/member/application/OauthService.java
> +                GoogleUser googleUser = googleOAuthService.getUserInfo(userInfoResponse);
저는 이 부분은 googleOAuthService.requestUserInfo를 private 메서드로 바꿔서 내부적으로 처리해도 괜찮지 않을까 생각이 듭니다!

즉, GoogleUser googleUser = googleOAuthService.getUserInfo(accessToken); 이렇게 토큰을 넣어 캡슐화를 올려도 좋을거 같습니다!

2024-02-04 14:58 UTC, somefood commented on src/main/java/choorai/excuseme/member/application/GoogleOAuthService.java
> +@Component
@Service로 선언 안 하고 Component로 선언한 이유가 궁금합니다~!

2024-02-04 15:23 UTC, somefood commented
> ## 3. 고민
> ### (1) Member가 가져야하는 정보
> 현재는 google에서 username만 가져와서, 해당 이메일의 존재여부를 기반으로 로그인 혹은 회원가입을 진행하는 상황입니다. 그런데 어떤 블로그에선 (이메일, provider)로 user를 식별하더라구요! 혹시 저희도 provider 정보를 추가해야할까요?? 카카오 oauth로 가져온 이메일 정보가 "~@gmail.com"일 가능성은 매우 적어보이지만 . . 유의미한 정보가 될 수도 있을 것 같아 의견 여쭤봅니다. (* provider라는 정보가 아래 3번 고민의 해결책이 되지 않을까 싶기도 합니데이)
> 
> ### (2) OAuth 로그인했을 때 신규 가입자인 경우 진행되는 로직
> 위에서 말씀드린대로, Oauth를 통해 가져온 username(이메일)이 기존에 등록되지 않은 username이면 memberService.register()를 타게 됩니다. 이 경우 register될 때 입력되는 password 값을 빈문자열("")로 지정해놓은 상황인데요. 이게 맞는건지 잘 모르겠습니다 🥹 서치를 엄청나게 해봤는데 딱히 찾아지는게 없었어서 .. 아시는 분 있으시면 의견 주심 감사드리겠습니다.
> 
> ### (3) 발생할 수 있는 문제 상황
> 이건 제가 구현하다가 생각한 건인데요 (위의 고민들과도 연결됩니다)
> 
> 유저 A가 "[a@gmail.com](mailto:a@gmail.com)"이라는 username, "a"라는 password로 일반로그인을 진행한 상황일 때 이 사람이 "[a@gmail.com](mailto:a@gmail.com)"으로 구글에 로그인을 해서 Google OAuth를 진행하게 된다면 (구글 OAuth는 처음 시도하는 상태) 자동으로 로그인 로직을 타게 됩니다. 하지만 OAuth에서 로그인 로직을 탈 때 input으로 들어가는 비밀번호가 빈 문자열("")이기 때문에 비밀번호 불일치로 로그인이 되지 않을 것입니다.
> 
> 이 경우 로그인이 안되는게 맞는건지, 아님 되어야하는건지...."일반회원가입 이후 로그인"과 "oauth 로그인"은 같은 username이라도 다른 유저로 보는 것이 맞는건지 .... 전혀 모르겠삽니다 ㅠ ㅠ 헷갈려요

---

고민 글도 잘 읽어보았습니다. 저도 사견을 드리자면...

1: 어험 그러네요. 다른 프로바이더로 동일 이메일로 회원가입하면 다른 회원으로 바라봐줘얄거 같으니,, 구분값이 필요할거 같은데,, 있으면 좋을거 같습니다!

2: 엄 사실 소셜로그인이니 패스워드 정보 없어도 될거 같은데,,, 대략 내부적으로 값  채워줘도 괜찮을거 같습니다!

3: 민주님이 현재는 자체 로그인 유저용의 login() 메서드를 사용하는데요. 고민하신대로 해당 메서드에선 비밀번호 체크를 사용하기에 oAuth용 로그인 메서드는 따로 만들어주는게 좋지 않을까 생각됩니다! 특정 예시지만 제가 이용하는 인프런의 경우엔 소셜로그인을 하고나서 개인 설정에서 따로 비밀번호를 추가할 수 있어서, 비밀번호를 설정하면 일반 로그인으로도 서비스를 이용할 수 있더라구요! 저희도 이렇게 사용할 수 있게 해줄거면 위 방식을 채택해도 좋을거 같습니다!

2024-02-05 12:57 UTC, JoungMinJu commented
> ### 1) Member가 가져야하는 정보
> 현재는 google에서 username만 가져와서, 해당 이메일의 존재여부를 기반으로 로그인 혹은 회원가입을 진행하는 상황입니다. 그런데 어떤 블로그에선 (이메일, provider)로 user를 식별하더라구요! 혹시 저희도 provider 정보를 추가해야할까요?? 카카오 oauth로 가져온 이메일 정보가 "~@gmail.com"일 가능성은 매우 적어보이지만 . . 유의미한 정보가 될 수도 있을 것 같아 의견 여쭤봅니다. (* provider라는 정보가 아래 3번 고민의 해결책이 되지 않을까 싶기도 합니데이)

넹 논의해서 oauth용 로그인 api를 따로 파게 된다면 member에 provider값 추가하는 것으로 진행하겠습니다 ! ! !

2024-02-05 14:17 UTC, JoungMinJu commented
- @Service 안쓴거, builder 어노테이션 활용 안한 거, 띄어쓰기 등등은 기냥 저의 실수라 . . 반영헀습니다 ^_____^

- 위에서 코멘트 달아놓은데로 @PathVariable 활용하도록(socialLoginType받아올 때) 변경했는데, 스프링부트 3.2부터 PathVariable 생략하려면 따로 -parameter 옵션을 명시적으로 설정해줘야하게 바꼈더라구요 [참조 링크](https://www.inflearn.com/questions/1087879/pathvariable-name-%EC%83%9D%EB%9E%B5-%EC%A7%88%EB%AC%B8-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4) 그래서 생략 안했습니다!

2024-02-06 14:55 UTC, JoungMinJu commented
### 추가

- accessToken 유효성 검증 로직 추가

2024-02-13 09:11 UTC, seokhwan-an requested changes
먼저 처음 해보는 소셜로그인을 구현하시느라 고생하셨습니다!👍👍
코드에 대한 의견과 질문 남겨 놓았습니다! 확인해주세요!
그리고 이는 리뷰 요청 시 고민해주신 점에 대한 의견을 남깁니다

### 1.  Member가 가져야하는 정보
여기서 말하는 Provider는 소셜 서비스에서 제공해주는 id 인가요?? 제가 말한 것이 맞다면 민주님이 말해주신 것처럼 id를 받아오는 것이 가장 사용자를 식별하는데 좋을 것 같지만 제 생각은 사용자가 구글로 로그인하고 추후에 다른 소셜 로그인으로 로그인을 하는 경우는 크게 없을 것 같다고 생각합니다. 그래도 민주님 말대로 가장 확실한 식별자는 이메일보다도 provider가 맞는 것 같습니다.(이것은 회의를 통해서 이야기 나눠보아요!)
### 2. OAuth 로그인했을 때 신규 가입자인 경우 진행되는 로직
현재는 비밀번호만 고려했는데 앞으로 일반 회원가입과 로그인이 생성되는 경우에는 사용자 정보도 포함되어야 할 것 같습니다. 비밀번호는 공백 문자열 보다는 내부적으로 제공해주는 것이 좋을 것 같습니다! (추후에 마이페이지에서 비밀번호를 변경할 수 있게 해주면 좋을 것 같습니다.)
### 3. 발생할 수 있는 문제 상황
이 부분은 석주님 말대로 소셜 로그인과 일반 로그인을 따로 분리해서 관리를 하는 것이 좋을 것 같습니다. 그리고 제 생각엔 같은 username(이메일)을 가지고 있으면 같은 유저로 보는 것이 좋을 것 같은데 이는 회의에서 이야기 나누면 좋을 것 같아요!

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/config/OAuthConfig.java
> +    }
restTemplate을 필요할 때마다 생성해서 사용하는 것이 아닌 bean으로 등록해서 이용한 것 좋네요!!👍👍
스프링 내부적으로 외부 서버와 통신하는 방식에는 민주님이 이용하신 restTemplate과 webClient가 있습니다. 혹시 이 두개 중에서 restTemplate을 이용하신 이유가 있나요?🤔

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/application/GoogleOAuthService.java
> +        log.info("Google User Info  = {}", userInfo);
구글에서 개인정보를 받아온 것을 로그로 남기는 것인데 이 부분 로그로 남기는 이유가 궁금합니다!

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/application/GoogleOAuthService.java
> +                String.class);
이 것도 궁금한 점인데 바로 GooleUser 객체로 받아오는 것이 아닌 String으로 받아와서 ObjectMapper를 통해 객체로 변경하는 이유가 궁금합니다! 지금 보면 goole로 부터 받아온 문자열을 변경하거나 수정하는 작업이 따로 없는 것 같아서 바로 GoogleUser로 받아도 괜찮을 것 같습니다!

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/application/OauthService.java
> +
공백 한줄 제거해 주세요!☺️

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/domain/dto/OAuthRequest.java
> +
공백 한줄 제거해주세요!

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/domain/dto/OAuthRequest.java
> +}
dto는 record로 변경해주세요!☺️

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/domain/oauth/GoogleUser.java
> +}
제가 봤을 땐 GoogleUser의 경우는 따로 데이터를 전달하는 용도로만 이용해서 dto와 같다는 생각이 드는데 이 파일을 dto 패키지 안에 넣는 것이 아닌 oauth라고 따로 패키지를 만드신 이유가 있을까요?

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/ui/MemberController.java
> +    @PostMapping("/oauth/login/{loginType}")
이 부분은 석주님이 말해주신 것과 같이 안드로이드와 합의를 보면 좋을 것 같습니다!

2024-02-13 09:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/member/application/OauthService.java
> +        }
이 부분은 추후에 카카오 로그인이 생기면 중복된 코드가 발생해 변화가 필요할 것 같은데 일단은 이렇게 두어도 괜찮을 것 같습니다!

2024-02-13 12:42 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/application/OauthService.java
> +        }
넵 카카오 로그인 구현할 때 고려해서 구현하겠습니다 ! !

2024-02-13 12:43 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/domain/oauth/GoogleUser.java
> +}
딱히 큰 이유는 없었는데 dto 에 넣는게 더 합리적인 것 같습니다 ^___^.. dto 패키지에 넣게 수정하겠습니다 ~ !~

2024-02-13 12:47 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/application/GoogleOAuthService.java
> +                String.class);
아 그러네요! 그 부분까진 생각 못했던 것 같습니다 고려해서 반영하겠습니다!!

2024-02-13 12:48 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/member/application/GoogleOAuthService.java
> +        log.info("Google User Info  = {}", userInfo);
어떤 정보가 넘어오는지 확인하고자 남기게 된 로그입니다 ! ! 운영환경상에선 필요가 없을 것 같기도하고 .. 그냥 지우는게 맞겠죠 . . ?

2024-02-13 12:48 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/global/config/OAuthConfig.java
> +    }
webclient를 모르고 있었습니다 ! 찾아보니 비동기 방식인 webclient가 더 선호된다고 하더라구요 자료 찾아보고 변경해보겠습니다 !

2024-02-25 15:18 UTC, xi-jjun commented on src/main/java/choorai/excuseme/global/config/OAuthConfig.java
> +    }
비동기 처리를 할 경우, 해당 데이터를 처리할 다른 서버가 필요하고 이는 서버의 분리가 필요하다는 의미여서 동기적으로 처리하는게 아마 편할거에요.

2024-02-25 15:20 UTC, xi-jjun commented on src/main/java/choorai/excuseme/member/application/GoogleOAuthService.java
> +        log.info("Google User Info  = {}", userInfo);
2월 25일 오늘 같이 얘기나누기도 했지만, 애매할 것 같으면 debug level로 내리고 로컬에서만 확인해도 무방할 것 같습니다.
그러나 해당 코드가 가독성 및 불필요하다라는 의견이 있다면 제거하는게 맞아보여요.

또한 해당 로그가 유저 관련 정보라면 민감 정보는 제외하고 로깅하는게 좋아보이네요 ㅎㅎ (비밀번호 등)

2024-02-25 15:21 UTC, xi-jjun commented on src/main/java/choorai/excuseme/member/ui/MemberController.java
> +    @PostMapping("/oauth/login")
`/oauth/{vendor}/login` 이 좀 더 좋아보이네요 ㅎㅎ

2024-02-25 15:25 UTC, xi-jjun commented on src/main/java/choorai/excuseme/member/application/OauthService.java
> +        }
해당 부분은 템플릿 메서드 패턴을 한번 써봐도 좋을 것 같다는 생각이 드네요..!
하지만 리팩터링의 영역일 것 같아서, 현재 PR말고 이후의 PR에서 진행하면 좋을 것 같습니다. (리뷰에 대한 복잡도를 낮춰서, 리뷰어들이 현재 OAuth 로그인이라는 목적의 코드를 몰입도 있게 리뷰할 수 있게하기 위함)

2024-02-25 15:34 UTC, xi-jjun commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +                .build();
매번 builder로 생성하는 것 보다는, `SignResponse` 클래스에 static 메서드를 선언해서 `foundMember`를 넘겨버려서 생성하는게 중복코드를 방지하기 좋아보이네요 :)

2024-02-26 15:21 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +                .build();
오 생각도 못했는데 좋은 방법인 것 같아요! !  반영하겠습니다!

2024-02-26 15:31 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +                .build();
@somefood @seokhwan-an  중복코드를 줄일 수 있다는 점에서 저는 위의 피드백이 합리적인 수정 방안이라고 생각하는데 어떻게 생각하시나요?!?
해당 방법을 진행하게 되면 SignResponse를 수정하게 되어서 MemberService도 건들게 되는데, 이 pr에서 리팩토링 진행해도 되는건지도 궁금합니다! (*MemberService는 이 pr에서 건드린 클래스가 아니어서 여쭤봅니다)

2024-03-03 15:25 UTC, JoungMinJu commented
@somefood @seokhwan-an 

reabse 관련 conflict 해결 커밋 올렸습니다!!

gender, birthdate, phoneNumber... 등 받아오는 것은 추후에 앞단이랑 논의해봐야할 것 같아서 일단은yml에 임시값 넣어놓고 그거 받아와서 생성하도록 구현해뒀어요!

2024-03-04 05:38 UTC, seokhwan-an requested changes
추가적인 코드 리뷰를 남겨서 확인하시고 수정부탁드립니다!

2024-03-04 05:38 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +    }
p1

현재 이 부분에서 2가지 문제가 발생하고 있습니다.
![image](https://github.com/choorai/excuse-me-backend/assets/70303795/d54051d5-ed68-4c32-904a-873d6f3d3875)
1. 트랜잭션이 붙은 메소드는 override가  가능해야한다는 에러(접근 제어자를 private에서 public으로 변경해야 합니다)
2. `@Transaction self-invocation`문제 이는 transaction이 실제로 동작하지 않는 것을 의미합니다.

2번 문제와 관련된 글은  [transaction-self invocation](https://velog.io/@park2348190/Spring-Transaction%EC%9D%98-Self-Invocation) , [spring 공식문서](https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/annotations.html)를 참고해주세요!
제가 이해한 대로 설명을 하면 기본적으로 `@transactional`은 AOP 기반으로 동작을 하고 우리가 작성한 객체가 아닌 이를 상속받은 proxy 객체를 이용한다고 합니다. 이를 외부에서 호출을 하면 proxy 객체를 통해서 접근을 하기에 `@Transactional` 이 붙은 메소드는 아래와 같은 형태로 동작한다고 합니다.
```java
// DB 커넥션 연결
Connection connection = dataSource.getConnection();
try (connection) {
    connection.setAutoCommit(false);

    // register 메소드 로직

    connection.commit();
} catch(SQLException e) {
    connection.rollback();
}
```
하지만 같은 객체(현재는 OauthService)에서 내부 method를 호출을 하게 되면 proxy 객체를 통해서 접근하는 것이 아니어서 transaction이 동작하지 않는다고 합니다.

2024-03-04 05:38 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +    }
위의 문제를 해결하기 위한 방법에는 event를 발생해서 memberService의 register를 호출하는 방법과 OauthService에서 memberService를 의존해서 memberService에서 구현된 register method를 이용하는 것이 대안이 될 수 있을 것 같습니다.

2024-03-04 05:38 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +        return login(signRequest);
p2

이 부분에서 굳이 signRequest를 만들어서 member를 저장하는 방식으로 처리하기 보다는 아래와 같이 바로 member 객체를 만들고 저장해보는 방법은 어떻게 생각하나요?
```java
final Optional<Member> findMember = memberRepository.findByUsername(new UserName(id));
if (findMember.isEmpty()) {
     final Member memberForSave = Member.createNormalMember(id,
                                                          passwordEncoder.encode(oauthPassword),
                                                          oauthName,
                                                          oauthGender,
                                                          oauthBirthDate,
                                                          oauthPhonenumber);
    memberRepository.save(memberForSave);
    return login(memberForSave);
   }
    return login(findMember.get());
```
위와 같이 수정되면 앞서서 문제가 되었던 register 메소드를 이용하지 않고도 member를 저장할 수 있습니다. 또한 login에서 불필요하게 db를 접근하는 요청이 사라지게 됩니다.

2024-03-04 05:38 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +    }
p2

기존의 코드는 db를 통해서 member를 조회하는 과정이 있는데 앞서서 제시한 `getOauthResponse`를 이용하게 되면 login에서도 SignRequest가 아닌 Member 객체를 파라미터로 받으면 되고 member 객체는 이미 실존하는 객체이므로 db에 접근할 필요없이 토큰을 만들면 될 것 같습니다.
```java
final String accessToken = jwtProvider.createToken(member.getUsername(), member.getRole());
return LoginResponse.of(member, accessToken);
```

2024-03-04 05:38 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +    private String oauthPhonenumber;
p1

이 부분 위에 `TODO : 클라이언트와 협의 후 처리`와 같이 주석을 달아주세요! 
앞으로 처리해야하는 부분에 대해서는 TODO 주석을 달아주는 것이 까먹지 않을 수 있어서 좋을 것 같습니다!

2024-03-04 05:38 UTC, seokhwan-an commented on src/test/java/choorai/excuseme/lecture/ui/LectureControllerTest.java
> +        final Member normalMember = Member.createNormalMember("excuseme", passwordEncoder.encode("excuseme"));
p1

이 부분은 제 실수로 member 객체를 현재 필드에 맞게 수정부탁드립니다. 어제 rebase 받고 수정했어야 했는데 실수로 넘겼었네요🙇‍♂️

2024-03-05 14:43 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +    }
아 꼼꼼한 리뷰 감사드립니다! 링크 걸어주신 덕분에 무슨 문제가 발생한건지 완전히 이해할 수 있었습니다 :)

해결법에 대해 생각해보자면
memberService 내의 register와 동일한 역할을 하고 있어서, 아래 방식으로 구현하는게 더 편할 것 같긴합니다!! 
근데  event를 발생시켜서 register를 호출하는 방식이 어떤 방식인지 궁금합니다!!

2024-03-05 14:46 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +    }
아 그리고 걸어주신 벨로그에서 TransactionTemplate을 사용하는 해결법을 보여주고 있는데 혹시 이 부분에 대해선 어떻게 생각하시나요?? 저는 처음보는 코드(?)여서 혹시 원래 알고 계시던 내용이신가 싶어 코멘트 남겨봅니다! @somefood @seokhwan-an

2024-03-05 15:03 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +        return login(signRequest);
질문 하나만 더 드리겠습니다!
코멘트 달아주신 코드로 변경하게 되었을 때, 불필요하게 db 접근하는 로직이 사라진다는게 어느 부분에서 사라지는 것인지 궁금합니다!

2024-03-05 15:07 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +    }
오 이 부분까지 고려해본다면 getOauthResponse를 직접 리팩토링하는 것이 더 좋아보이네요!

@Transaction 문제나 db에 두 번씩 접근하는 부분을 고려한다면 getOauthResponse를 수정하는 것이 가장 합당해보이니 이와 같이 수정하도록 하겠습니다!

2024-03-06 09:58 UTC, somefood approved these changes

2024-03-06 14:45 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/oauth/application/OauthService.java
> +    }
TransactionTemplate을 다루어보지 않았지만 특수한 상황이 아니면 저는 개인적으로 transaction을 코드 level에서 직접 다루는 것은 많은 사이드 이팩트를 불러올 거 같습니다. 그래서 먼저 충분하게 학습해봐야 할 것 같습니다.

2024-03-06 14:48 UTC, seokhwan-an approved these changes
민주님 이번에 처음으로 소셜 로그인을 구현해보신다고 했는데
잘 구현해 주신 것 같습니다!! 👍👍

리뷰 반영하신 것 모두 확인했습니다!

2024-03-06 15:01 UTC, merged