Feature/#25 create lecture
choorai/excuse-me-backend pull request #26
Opened 2024-02-18 15:13 UTC by somefood

- close #25 

수업 도메인을 구성하고, 조회 및 시청하기 기능을 구현했습니다.

엔티티 구성은 다음과 같습니다.

<img width="332" alt="image" src="https://github.com/choorai/excuse-me-backend/assets/24751937/628be856-0f10-42f9-8c29-a94a0d365a3e">

그리고 API는 다음과 같습니다.

- GET /lectures:  수업 리스트 전체 조회
<img width="328" alt="image" src="https://github.com/choorai/excuse-me-backend/assets/24751937/cb3ad157-32dc-4598-8b3c-24e23386b836">

- GET /lectures/{lectureId}: 수업 상세 조회 
<img width="499" alt="image" src="https://github.com/choorai/excuse-me-backend/assets/24751937/23795202-7db9-4f17-adf2-c7268e1a9ec8">

- POST /lectures/{lectureId}: 시청하기
<img width="581" alt="image" src="https://github.com/choorai/excuse-me-backend/assets/24751937/e72bc670-8de4-4b36-accf-4c33877e45a8">

고민 사항으론 전체 조회나 상세 조회에서 수업 별로 사용자 본인의 시청 상황을 같이 첨부해주는게, UI에서 표시해 줄때 좋은거 같은데
해줄지 말지 고민하다가 우선 안 보이게 해서 올렸습니다. 보시고 의견 주시면 감사하겠습니다! :)

2024-02-20 07:05 UTC, seokhwan-an requested changes
먼저 lecture 관련한 기능을 구현하시느라 고생하셨습니다!👍👍 
코드와 관련된 질문을 남겨 놓았습니다!
그리고 현재 테스트 코드에 대해서 고민이 많으신 것으로 알고 있는데 일단은  인수테스트를 우선으로 작성해보는 것을 추천합니다!! (이 부분의 경우 회의를 통해서 구체적으로 어떻게 할지 정해보면 좋을 것 같아요!)

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/lecture/application/LectureService.java
> +        );
현재 이 메소드에서는 Member를 따로 이용하지 않는 것 같은데 필드에 member를 두신 이유가 궁금합니다!
그리고 여기는 파라미터에 final이 붙어있지 않네요 final 붙여 주세요!!

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/lecture/application/LectureService.java
> +
```suggestion
        MemberLecture memberLecture = memberLectureRepository.findByMemberAndLecture(member, foundLecture)
            .orElseGet(() -> memberLectureRepository.save(new MemberLecture(member, foundLecture)));

```
위의 코드를 이와 같이 수정하면 더 깔끔할 것 같아요!

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/lecture/domain/dto/LectureRequest.java
> +}
response의 경우에는 record를 이용했는데 request의 경우에는 record를 이용하지 않은 이유가 있을까요?

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +    public ResponseEntity<LectureDetailResponse> getLectureById(@AuthenticationPrincipal(expression = "member") final Member member, @PathVariable(name = "lectureId") final Long lectureId) {
스프링 시큐리티에서는 `@AuthenticationPrincipal`를 통해서 인증된 회원정보를 불러올 수 있네요! 배워갑니다!!👍

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/memberlecutre/domain/MemberLecture.java
> +    private ProgressStatus progressStatus;
혹시 columnDefinition을 설정해두신 이유가 있나요?

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/memberlecutre/domain/repository/MemberLectureRepository.java
> +//    Optional<MemberLecture> findByMemberIdAndLectureId(@Param("memberId") Long memberId, @Param("lectureId") Long lectureId);
이 부분의 경우 이용하지 않기에 지워도 될 것 같습니다!☺️

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/resources/db/migration/V20240218_1725__create_member_lecture.sql
> +    progress_status VARCHAR(255)          NOT NULL,
Progress_status의 경우 enum 타입으로 저장하는 것이 아닌 varchar로 두신 이유가 있을까요?

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/lecture/exception/LectureException.java
> +
띄어쓰기가 2줄이네요! 한 줄은 지워주세요!!☺️

2024-02-20 07:05 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +                configurer.requestMatchers("/actuator/**", "/error/**").permitAll()
혹시 `/error`는 어떤 경우에 이용되는 것일까요?🤔

2024-02-22 03:22 UTC, somefood commented on src/main/java/choorai/excuseme/memberlecutre/domain/repository/MemberLectureRepository.java
> +//    Optional<MemberLecture> findByMemberIdAndLectureId(@Param("memberId") Long memberId, @Param("lectureId") Long lectureId);
제가 정신없이 올리다가 지우는걸 까먹었군요. 반영하겠습니다!

2024-02-22 03:26 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/application/LectureService.java
> +        );
넵넵 final 붙이도록 하겠습니다!

엄 제가 처음에 메서드를 구성할때, Member를 활용해서 상세보기에서도 해당 멤버의 수강 기록 데이터를
같이 갖고 오면 좋지 않을까 생각해서 넣었던 겁니다.
근데 아직은 필요없을거 같아서 다시 제거해서 올리도록 하겠습니다! ㅎㅎ

2024-02-22 03:46 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/application/LectureService.java
> +
감사합니다. 제가 optional을 썼는데, 깔끔하게 못 짰는데 참고하겠습니다 ㅎㅎㅎ

2024-02-22 03:47 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +    public ResponseEntity<LectureDetailResponse> getLectureById(@AuthenticationPrincipal(expression = "member") final Member member, @PathVariable(name = "lectureId") final Long lectureId) {
맞습니다. SecurityContextHolder안에 쓰레드로컬 형태로 관리되고 있을꺼라 이런 어노테이션으로 꺼내 쓸 수 있을겁니다! ㅎㅎ

2024-02-22 03:53 UTC, somefood commented on src/main/java/choorai/excuseme/memberlecutre/domain/MemberLecture.java
> +    private ProgressStatus progressStatus;
제가 이전에 Member 엔티티 만들때 enum으로 해두나 jpa validator에 걸려서 DDL 작성시 enum으로 했었습니다.
근데, 다른 방법을 찾아보니 columnDefinition을 활용하면 엔티티와 DB 둘다 문자열 타입으로 받을 수 있더라구요 ㅎㅎ

이 방식을 차용해본 이유는, 
enum으로 관리하게 되면 업데이트가 필요한 경우 DB의 컬럼에서도 계속 enum 항목을 추가해주어야 하니 DDL을 작성해야는 번거로움이 발생합니다. 하지만 이처럼 VARCHAR로 선언하는 경우, 자바 코드 내에서만 관리하면 되니 좀 더 용이하지 않을까 해서 이렇게 해보았습니다.
이 부분은 저희 팀끼리 얘기해서 정하면 좋을거 같습니다! ㅎㅎ

2024-02-22 03:54 UTC, somefood commented on src/main/resources/db/migration/V20240218_1725__create_member_lecture.sql
> +    progress_status VARCHAR(255)          NOT NULL,
https://github.com/choorai/excuse-me-backend/pull/26#discussion_r1495320624

상기 내용과 같은 이유로 varchar로 선언했습니다 :)

2024-02-22 04:00 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/domain/dto/LectureRequest.java
> +}
아 저는 request로 받을때는 안될줄 알았는데 되는군요..! ㅎㅎ
바로 바꾸겠습니다 ㅎㅎㅎ

2024-02-22 04:17 UTC, somefood commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +                configurer.requestMatchers("/actuator/**", "/error/**").permitAll()
/error를 사용한 이유는 제가 URL을 오기재 해버렸던 경험이 있는데, (/lectures를 /lectures 로...)
NOT FOUND인 경우 스프링이 내부적으로 /error로 포워딩 되는거 같습니다.
추가 안 했을 때의 request를 보니 rolePrefix = "ROLE_"로 전송되는데, 이런 경우 비인가로 처리되기 때문에 AuthenticationEntryPoint의 구현체로 이동해서 처리가 됩니다. 

사실 그대로 두어도 될거 같긴 한데,, /error인 경우 저희가 커스텀 에러 처리를 따로 한 경우가 없다보니 우선은 날것(?) 그대로 보여주자는 취지로 추가하게 되었습니다! 

아래 사진들 첨부드리오니 보시면 더 이해가 쉬울 것입니다!

![image](https://github.com/choorai/excuse-me-backend/assets/24751937/5f689a29-bbfb-4760-bba0-cb3ad3c4f84e)

- /error 추가 안 했을 때의 디버깅 장면

![image](https://github.com/choorai/excuse-me-backend/assets/24751937/218ee3f3-460c-4f87-bb21-de83b1e50d26)

- /error 추가 안 했을 때의 응답값

![image](https://github.com/choorai/excuse-me-backend/assets/24751937/799f38c2-0f90-4c89-a39e-931caaba2896)

- /error 추가했을 때의 응답값

2024-02-22 06:11 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/global/config/SecurityConfig.java
> +                configurer.requestMatchers("/actuator/**", "/error/**").permitAll()
아하 security에서 `/error`를 허용하지 않으면 아래와 같은 문제가 발생할 수 있군요! 디버깅 결과를 제시해주셔서 쉽게 이해했습니다!👍

2024-02-23 06:15 UTC, somefood commented on src/main/java/choorai/excuseme/memberlecutre/domain/MemberLecture.java
> +    private ProgressStatus progressStatus;
해당 부분은 2024.02.22에 팀원들끼리 enum으로 관리해서 데이터 정합을 높이는 방법으로 정했음

2024-02-25 13:07 UTC, xi-jjun requested changes

2024-02-25 13:07 UTC, xi-jjun commented on src/main/java/choorai/excuseme/memberlecutre/domain/MemberLecture.java
> +    @ManyToOne
기본값이 EAGER fetch여서 LAZY로 바꿔주시면 좋을 것 같아요~!

2024-02-25 15:37 UTC, xi-jjun commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +    public ResponseEntity<LectureDetailResponse> getLectureById(@AuthenticationPrincipal(expression = "member") final Member member, @PathVariable(name = "lectureId") final Long lectureId) {
미친... 한 수 배워갑니다...

2024-02-25 15:48 UTC, xi-jjun commented on src/main/java/choorai/excuseme/global/security/CustomUserDetails.java
> +    }
해당 메서드의 사용처가 어딘지 알 수 있을까요?

2024-02-25 15:48 UTC, xi-jjun commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +        return new ResponseEntity<>(lectureResponses, HttpStatus.OK);
[Nit] 참고차 공유드리자면, static method도 있습니다 ㅎㅎ
```java
return ResposneEntity.ok(lectureResponse);
```

2024-02-25 15:48 UTC, xi-jjun commented on src/main/resources/db/migration/V20240218_1720__create_lecture.sql
> +);
강의는 name으로 검색이 많이 될 수 있을 것 같은데요, 관련해서 index 추가 검토해주셨으면 좋겠씁니다

2024-02-25 15:48 UTC, xi-jjun commented on src/main/resources/db/migration/V20240218_1725__create_member_lecture.sql
> +);
FK를 설정하는 것보다 application level에서 연관관계를 매핑해주는게 좋다고 저 개인적으로는 생각하지만, 필요하면 써야한다고도 생각합니다. 저는 서버 개발을 하고 있지는 않아서 이 이상의 리뷰는 드리면 안될 것 같아서, 판단은 자유롭게 해주시면 감사하겠습니다.

해당 테이블은 member_id, lecture_id로 검색이 많이 될 것 같은데요, 관련해서 index 추가 고려해주시면 감사하겠습니다.

2024-02-26 15:18 UTC, JoungMinJu reviewed
리뷰를 열심히 남기려고 했는데 궁금증이 더 많은 것 같네요 😅
늦게 확인해서 죄송합니다 수고많으셨어요!!

2024-02-26 15:18 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +        List<LectureResponse> lectureResponses = lectureService.getLectures();
(단순 궁금증이라 pn표시 안했습니다)

이렇게 service 통해서 받아오는 값(해당 코드의 경우엔 List<LectureResponse>)은 따로 final 키워드 안붙혀도 되는건가요??

2024-02-26 15:18 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/lecture/application/LectureService.java
> +@Transactional(readOnly = true)
(질문)

@Transactional(readOnly=true)는 단순 조회에서만 사용되는 것으로 알고 있는데요! 해당 서비스 아래에 watchLecture()메소드에서 lecture 값에 대한 update가 이뤄지고 있는 것 같은데, 이경우엔 문제가 안되는걸까요...? 정상 동작하는 것은 확인했는데 제가 뭘 잘못알고있는지 궁금해서 여쭤봅니다 ! ! ! ! 가르침을주셔요 . . . .

2024-02-26 15:18 UTC, JoungMinJu commented on src/main/java/choorai/excuseme/lecture/application/LectureService.java
> +import java.util.Optional;
P1

불필요 import문 지워주세요!

2024-02-27 06:52 UTC, somefood commented on src/main/java/choorai/excuseme/memberlecutre/domain/MemberLecture.java
> +    @ManyToOne
넵 적용하겠습니다~!

2024-02-27 06:56 UTC, somefood commented on src/main/java/choorai/excuseme/global/security/CustomUserDetails.java
> +    }
해당 메서드는 **@AutenticationPrinciapl** 어노테이션의 expression 필드를 위해 사용했습니다~!
해당 필드를 적용하지 않으면 컨트롤러에서 Principal을 갖고 오기 때문에 Member를 사용해주려면 형변환 같은 작업을 해주어야 하는데, 저렇게 프로퍼티 메서드를 선언하여 expression에서 사용하면 바로 Member 엔티티로 바꾸어 꺼내주기에 사용해봤습니다 ㅎㅎ

`public void watchLecture(@AuthenticationPrincipal(expression = "member") final Member member`

2024-02-27 07:00 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +        return new ResponseEntity<>(lectureResponses, HttpStatus.OK);
감사합니다. 더 사용하기 좋은 스태틱 메서드가 제공되는군요~!
이걸로 한 번 바꿔봤습니다 ㅎㅎ. 감사합니다~!

2024-02-27 07:01 UTC, somefood commented on src/main/resources/db/migration/V20240218_1725__create_member_lecture.sql
> +);
넵 이런 부분은 계속 논의 해보면서 변경해보는 방향으로 나아가보자 합니다~!
저도 항상 고민이 되는 부분인데 관계를 정의해서 정합성을 중시할 것인지, 디비 내에서는 자유도를 높일 것인지 참 어려운 부분 같습니다.
경험을 계속 쌓아봐야겠습니다 ㅎㅎ
index는 재준님이 말씀주신대로 필요할거 같아 추가해보겠습니다~!

2024-02-27 07:03 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/application/LectureService.java
> +import java.util.Optional;
넵 불필요한 import 지웠습니다~! :)

2024-02-27 07:10 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +        List<LectureResponse> lectureResponses = lectureService.getLectures();
아하 이거는 인텔리제이 설정 전이라 final 붙이는걸 자꾸 까먹었네유 ㅠㅠ
확인 감사드리며, final들 붙여놨습니다! 누락된데 있으면 언제든 편히 말씀 주세요~! ㅎㅎㅎ

2024-02-27 07:41 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/application/LectureService.java
> +@Transactional(readOnly = true)
어엄 그래서 watchLecture 메서드 위에 transactional 어노테이션을 따로 추가했습니다~!
만일 제가 메서드에 해당 어노테이션을 걸어두지 않았다면 아래와 같은 에러가 발생하면서 제기능이 안됐을 겁니다 ㅎㅎ

`Connection is read-only. Queries leading to data modification are not allowed`

2024-02-29 11:35 UTC, seokhwan-an requested changes
먼저 테스트를 작성해주셔서 감사합니다!
이번에 작성해주신 테스트 코드에 대해서 주로 리뷰 남겼습니다. 
천천히 확인해 주세요!

2024-02-29 11:35 UTC, seokhwan-an commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +    }
p3

다시 코드를 리뷰하다가 보았는데요 혹시 이 부분은 응답 객체를 반환하지 않으신 이유가 있으신가요?

2024-02-29 11:35 UTC, seokhwan-an commented on src/test/java/choorai/excuseme/lecture/ui/LectureControllerTest.java
> +    private int port;
p1

현재 이 부분과 밑에 `@BeforeEach`는 인수테스트를 작성하는데 중복으로 작성해야하는 부분이어서 제가 전에 test안에 support 패키지 내부에 `AcceptanceTest`에 포함되어 있어서 그 부분을 상속받아서 이용하면 될 것 같아요!

2024-02-29 11:35 UTC, seokhwan-an commented on src/test/java/choorai/excuseme/lecture/ui/LectureControllerTest.java
> +    @WithMockUser(roles = "USER")
p2

`@WithMockUser`는 없어도 테스트는 잘 돌아가는데 혹시 `@WithMockUser`를 이용하신 이유가 있으신가요?
혹시 참고하신 래퍼런스도 같이 공유해주시면 좋을 것 같아요!

2024-02-29 11:35 UTC, seokhwan-an commented on src/test/java/choorai/excuseme/lecture/ui/LectureControllerTest.java
> +        assertThat(registeredMemberLecture).isNotEmpty();
p1

결국 밑에서 실제 값을 비교하는 검증사항이 있으니 이 부분은 따로 검증하지 않아도 괜찮을 것 같습니다!

2024-03-01 15:18 UTC, somefood commented on src/test/java/choorai/excuseme/lecture/ui/LectureControllerTest.java
> +    @WithMockUser(roles = "USER")
이것저것 테스트해보면서 넣었던건데, 실수로 안 지워졌군요..! 지워서 반영하겠습니다! ㅎㅎ

2024-03-01 15:18 UTC, somefood commented on src/test/java/choorai/excuseme/lecture/ui/LectureControllerTest.java
> +        assertThat(registeredMemberLecture).isNotEmpty();
넵! 알겠습니다! ㅎㅎ

2024-03-01 15:21 UTC, somefood commented on src/test/java/choorai/excuseme/lecture/ui/LectureControllerTest.java
> +    private int port;
넵 알겠습니다! 석환님이 만든 AcceptanceTest를 참고해서 위 코드에 넣었던건데, 상속받는 형태로 바꾸겠습니다 ㅎㅎ
궁금한 점이 있는데,
@LocalServerPost 용도가 무엇인지 궁금하고,
RestAssured.port = port를 사용하는 이유도 궁금합니다!

LocalServerPort를 사용하면 RANDOM_PORT의 포트 넘버가 들어가는 형태일려나요~??

2024-03-01 15:23 UTC, somefood commented on src/main/java/choorai/excuseme/lecture/ui/LectureController.java
> +    }
응답 객체를 반환하지 않으면, Http Status가 200으로 내려지길래 안 넣었습니다!
명시적으로라도 ResponseEntity<Void>로 넣는게 좋을까요~?

2024-03-03 13:57 UTC, JoungMinJu approved these changes
수고하셨습니다!

2024-03-03 13:57 UTC, seokhwan-an approved these changes
강의 관련된 코드 작성하시느라 고생하셨습니다!👍👍
리뷰 반영하신 것 확인했습니다!

2024-03-03 14:01 UTC, merged